version: "3.9"
services:
  api-rest-service-1:
    image: api_rest
    container_name: api-rest-container-1
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8081:8080
    env_file:
      - .env
    depends_on:
      - redis
  api-rest-service-2:
    image: api_rest
    container_name: api-rest-container-2
    ports:
      - 8082:8080
  redis:
    image: redis/redis-stack-server
    container_name: redis-container
  redis-data:
    image: redis
    container_name: redis-data-container
    volumes:
      - ./data.sql:/data.sql
    command: sh -c "redis-cli -h redis < /data.sql"
    depends_on:
      - redis
  api-data:
    image: alpine/curl
    container_name: api-data-container
    volumes:
      - ./dogs:/dogs
      - ./init.sh:/init.sh
    entrypoint: sh -c "/init.sh"
    depends_on:
      - api-rest-service-1
